name: C/C++ CI

on: [push, pull_request]

env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache/

jobs:
  linux-x64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Restore Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          cache-name: linux-x86_64
        continue-on-error: true
      - name: build-linux-editor-x64
        run: |
          pip3 install --user scons
          scons platform=linux target=editor generate_bindings=yes -j $(nproc)
          ldd demo/addons/godot-git-plugin/linux/*.so
      - name: Save Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          cache-name: linux-x86_64
      - uses: actions/upload-artifact@v4
        with:
          name: libgit_plugin.linux.x86_64.editor.so-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/

  windows-x64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Restore Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          cache-name: windows-x86_64
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          architecture: "x64"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build-windows-editor-x64
        run: |
          pip3 install --user scons
          scons platform=windows target=editor generate_bindings=yes -j $env:NUMBER_OF_PROCESSORS
          dumpbin /dependents .\demo\addons\godot-git-plugin\win64\*.dll
      - name: Save Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          cache-name: windows-x86_64
      - uses: actions/upload-artifact@v4
        with:
          name: libgit_plugin.windows.x86_64.editor.dll-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/

  macos-universal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Restore Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          cache-name: macos-universal
      - name: build-macos-editor-universal
        run: |
          brew install scons
          scons platform=macos target=editor generate_bindings=yes macos_arch=universal use_llvm=yes macos_deployment_target=10.13 -j $(sysctl -n hw.logicalcpu)
          otool -L demo/addons/godot-git-plugin/macos/*.dylib
      - name: Save Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          cache-name: macos-universal
      - uses: actions/upload-artifact@v4
        with:
          name: libgit_plugin.macos.universal.editor.dylib-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/
