name: clang-format

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: "godot-git-plugin/src"
          extensions: "h,cpp"
          clangFormatVersion: 11
